@url = https://localhost:7240/orders-module/cart
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzZlM2JlOC02NGE1LTQ0NzItOGYzMy1lY2M2MWMzODZiMTMiLCJ1bmlxdWVfbmFtZSI6IjIzNmUzYmU4LTY0YTUtNDQ3Mi04ZjMzLWVjYzYxYzM4NmIxMyIsImVtYWlsIjoidGVzdG93eTEyM0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwibmJmIjoxNzA0Mjk2OTI5LCJleHAiOjE3MDQzMDA1MjksImlzcyI6Im5ldHN0b3JlIiwiYXVkIjoibmV0c3RvcmUifQ.VEYv2mSHhtH8JuOscyKlDmiyI4O5XECXI5l6oNctJl4


POST {{url}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "id": "f74a5631-271d-40dc-be48-7ae5cf2dd159",
    "quantity": 1
}

###

DELETE {{url}}?codeName=1996-nuptse-xl-blue-adult&quantity=3
Authorization: Bearer {{jwt}}

###

DELETE {{url}}/clear
Authorization: Bearer {{jwt}}

###

GET {{url}}
Authorization: Bearer {{jwt}}

###

PUT {{url}}/checkout
Authorization: Bearer {{jwt}}