@url = https://localhost:7240/orders-module/cart
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNjRlMzUyMC04MTkyLTQ4OGQtOWJlNC02NzdlODE1YWE4MjkiLCJ1bmlxdWVfbmFtZSI6IjA2NGUzNTIwLTgxOTItNDg4ZC05YmU0LTY3N2U4MTVhYTgyOSIsImVtYWlsIjoidGVzdDFkMkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwibmJmIjoxNzA5NTUxNTAzLCJleHAiOjE3MDk2Mzc5MDMsImlzcyI6Im5ldHN0b3JlIiwiYXVkIjoibmV0c3RvcmUifQ.wyXcTfOpmr-Bpy0tC_5NmAqlpimiUVb1ux4wwFJFYcc


POST {{url}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "id": "f74a5631-271d-40dc-be48-7ae5cf2dd159",
    "quantity": 1
}

###

DELETE {{url}}?codeName=1996-nuptse-xl-blue-adult&quantity=3
Authorization: Bearer {{jwt}}

###

DELETE {{url}}/clear
Authorization: Bearer {{jwt}}

###

GET {{url}}
Authorization: Bearer {{jwt}}

###

PUT {{url}}/checkout
Authorization: Bearer {{jwt}}