@url = https://localhost:7240/products-module
@id = b921c627-6446-45fb-a454-b17d9b9b8543

@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZjM3MTY3OS1hZTM3LTRmMGYtOTYwOS1kZjgxNzNlYjM0MmEiLCJ1bmlxdWVfbmFtZSI6ImJmMzcxNjc5LWFlMzctNGYwZi05NjA5LWRmODE3M2ViMzQyYSIsImVtYWlsIjoidGVzdG93eTEyM0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsIm5iZiI6MTcwMDkyNjA4MywiZXhwIjoxNzAxMDEyNDgzLCJpc3MiOiJuZXRzdG9yZSIsImF1ZCI6Im5ldHN0b3JlIn0._Hd_BHT5Mlp9lxacxzCt9vwY2BHGumfPte0UZR-gVbA

GET {{url}}/products

###

POST {{url}}/products
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "Name": "Intel i9-11900k",
    "Description": "A series of microprocessors based on the x64 architecture",
    "Categories": [
         "computer-part" 
    ],
    "Price": 1900,
    "Discount": 20
}

###

GET {{url}}/products/{{id}}

###

PATCH {{url}}/products/{{id}}
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "Discount": 11
}

###

DELETE {{url}}/products/{{id}}
Authorization: Bearer {{jwt}}