@url = https://localhost:7240/products-module
@id = 797d056d-85ec-468a-b7e5-8330df78e411
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNzM2MDEyMi0wMWM1LTRkMmUtOGQ3Ny1hZTU3ODVkMGIwYWUiLCJ1bmlxdWVfbmFtZSI6ImM3MzYwMTIyLTAxYzUtNGQyZS04ZDc3LWFlNTc4NWQwYjBhZSIsImVtYWlsIjoidGVzdG93eUBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsIm5iZiI6MTcwMDY3MzQxOCwiZXhwIjoxNzAwNzU5ODE4LCJpc3MiOiJuZXRzdG9yZSIsImF1ZCI6Im5ldHN0b3JlIn0.bex7lPLmC3C9BagI4oWBtZhWWZrabfz4VpopgsqV27o

GET {{url}}/products

###

POST {{url}}/products
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "Name": "Intel i9-11900k",
    "Description": "A series of microprocessors based on the x64 architecture",
    "Categories": [
         "computer-part" 
    ],
    "Price": 1900,
    "Discount": 20
}

###

GET {{url}}/products/{{id}}

###

PATCH {{url}}/products/{{id}}
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "Discount": 11
}

###

DELETE {{url}}/products/{{id}}
Authorization: Bearer {{jwt}}