@url = https://localhost:7240/products-module
@id = 99c0b55b-c33d-483c-886d-e5f719c7e846

@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOTU0N2IxYy05ZDgxLTRlOGEtOTRkYS00YjZjODhiNTYwMGEiLCJ1bmlxdWVfbmFtZSI6ImY5NTQ3YjFjLTlkODEtNGU4YS05NGRhLTRiNmM4OGI1NjAwYSIsImVtYWlsIjoidGVzdG93eTEyMzRAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJuYmYiOjE3MDEwMjg2OTUsImV4cCI6MTcwMTExNTA5NSwiaXNzIjoibmV0c3RvcmUiLCJhdWQiOiJuZXRzdG9yZSJ9.212JF_lumBpK7-cdcOk0W9KKVU88c07SSPKnR0ooEVA

GET {{url}}/products

###

POST {{url}}/products
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "Name": "Intel i9-11900k",
    "Description": "A series of microprocessors based on the x64 architecture",
    "Categories": [
         "computer-part" 
    ],
    "Price": 1900,
    "Discount": 20
}

###

GET {{url}}/products/{{id}}

###

PATCH {{url}}/products/{{id}}
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "Discount": 11
}

###

DELETE {{url}}/products/{{id}}
Authorization: Bearer {{jwt}}