@url = https://localhost:7240/users-module/users
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NTI1OTJmMC0wODVlLTQxNDktYjFhMy1hYWYzNWU5YWE4YzUiLCJ1bmlxdWVfbmFtZSI6IjQ1MjU5MmYwLTA4NWUtNDE0OS1iMWEzLWFhZjM1ZTlhYThjNSIsImVtYWlsIjoidGVzdG93eTEyM0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsIm5iZiI6MTcwMTk1Nzg4NiwiZXhwIjoxNzAyMDQ0Mjg2LCJpc3MiOiJuZXRzdG9yZSIsImF1ZCI6Im5ldHN0b3JlIn0.v3k2eW9JzQ774X3NgcFgUqkSo-UAoB4-BFWwauG-nGU

POST {{url}}/sign-up
Content-Type: application/json

{
    "email": "testowy123@gmail.com",
    "username": "test123",
    "password": "Test123!"
}

###

POST {{url}}/sign-in
Content-Type: application/json

{
    "username": "test123",
    "password": "Test123!"
}

###

GET {{url}}
Authorization: Bearer {{jwt}}


###

DELETE {{url}}/452592f0-085e-4149-b1a3-aaf35e9aa8c5
Authorization: Bearer {{jwt}}
