@url = https://localhost:7240/users-module/users
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOTU0N2IxYy05ZDgxLTRlOGEtOTRkYS00YjZjODhiNTYwMGEiLCJ1bmlxdWVfbmFtZSI6ImY5NTQ3YjFjLTlkODEtNGU4YS05NGRhLTRiNmM4OGI1NjAwYSIsImVtYWlsIjoidGVzdG93eTEyMzRAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoidXNlciIsIm5iZiI6MTcwMTAyNTQzMSwiZXhwIjoxNzAxMTExODMxLCJpc3MiOiJuZXRzdG9yZSIsImF1ZCI6Im5ldHN0b3JlIn0.E05gJPxuMDwigO1dW3TuaOG5rkcxTend2C3a7SHGoNM

POST {{url}}/sign-up
Content-Type: application/json

{
    "email": "testowy1234@gmail.com",
    "username": "test1234",
    "password": "Test123!"
}

###

POST {{url}}/sign-in
Content-Type: application/json

{
    "username": "test123",
    "password": "Test123!"
}

###

GET {{url}}
Authorization: Bearer {{jwt}}


###

DELETE {{url}}/0520f172-e0e8-4db0-87f3-a740d25595e6
Authorization: Bearer {{jwt}}
