@url = https://localhost:7240/customers-module/customers
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNzZmYzgyOC05YTgxLTQ5MjktYTliNS1kMTJmNWE1ZDUwODgiLCJ1bmlxdWVfbmFtZSI6IjI3NmZjODI4LTlhODEtNDkyOS1hOWI1LWQxMmY1YTVkNTA4OCIsImVtYWlsIjoidGVzdG93eTEyM0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsIm5iZiI6MTcwMjgyNjAzNiwiZXhwIjoxNzAyODI5NjM2LCJpc3MiOiJuZXRzdG9yZSIsImF1ZCI6Im5ldHN0b3JlIn0.dy9TbriZa7seXND1n-0u7okqkfdQ5hepHMNhktPcpLc

PUT {{url}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "firstName": "Jack",
    "LastName": "Sparrow",
    "Address": 
    {
        "Country": "Poland",
        "City": "Krakow",
        "Street": "Testowa",
        "PostalCode": "80-180"
    }
    
}

###

GET {{url}}
Authorization: Bearer {{jwt}}