@url = https://localhost:7240/customers-module/customers
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzFkN2ZkZi1iZDM0LTQyNGEtYjFlZS03OGVjODI0NGZmMmUiLCJ1bmlxdWVfbmFtZSI6IjY3MWQ3ZmRmLWJkMzQtNDI0YS1iMWVlLTc4ZWM4MjQ0ZmYyZSIsImVtYWlsIjoidGVzdG93eTEyM0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwibmJmIjoxNzAxMjAwMTg2LCJleHAiOjE3MDEyODY1ODYsImlzcyI6Im5ldHN0b3JlIiwiYXVkIjoibmV0c3RvcmUifQ.Z8lTHbjtMB9nf3EEdeytz-VPx9izYIAZyEAVCUDNY9M

PUT {{url}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "firstName": "Jack",
    "LastName": "Sparrow",
    "Address": 
    {
        "Country": "Poland",
        "City": "Krakow",
        "Street": "Testowa",
        "PostalCode": "80-180"
    }
    
}

###

GET {{url}}
Authorization: Bearer {{jwt}}