@url = https://localhost:7240/catalogs-module/brands
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZWFiNzAzMi1mOTAzLTRkZTktYTg5Yi01YzhlODE0YTE2MDYiLCJ1bmlxdWVfbmFtZSI6ImJlYWI3MDMyLWY5MDMtNGRlOS1hODliLTVjOGU4MTRhMTYwNiIsImVtYWlsIjoidGVzdG93eTEyM0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsIm5iZiI6MTcwMzE2OTgzNSwiZXhwIjoxNzAzMTczNDM1LCJpc3MiOiJuZXRzdG9yZSIsImF1ZCI6Im5ldHN0b3JlIn0.C1p1zakw4yyaDOdhrvXubfC3aVnExp978SndUelvCTQ

POST {{url}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "name": "The North Face"
}

###

GET {{url}}