@url = https://localhost:7240/catalogs-module/products
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NTI1OTJmMC0wODVlLTQxNDktYjFhMy1hYWYzNWU5YWE4YzUiLCJ1bmlxdWVfbmFtZSI6IjQ1MjU5MmYwLTA4NWUtNDE0OS1iMWEzLWFhZjM1ZTlhYThjNSIsImVtYWlsIjoidGVzdG93eTEyM0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsIm5iZiI6MTcwMTk1Nzg4NiwiZXhwIjoxNzAyMDQ0Mjg2LCJpc3MiOiJuZXRzdG9yZSIsImF1ZCI6Im5ldHN0b3JlIn0.v3k2eW9JzQ774X3NgcFgUqkSo-UAoB4-BFWwauG-nGU

POST {{url}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "mockupid": 1,
    "count": 1,
    "agecategory": "Adult",
    "size": "M",
    "Color": "Black",
    "price": 1299
}

###

GET {{url}}?getby=brand&value=The%20North%20Face


###

GET {{url}}

###

GET {{url}}?getby=category&value=Down%20jackets