@url = https://localhost:7240/catalogs-module/products
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Nzc5NzQwZC1kMDIxLTQ5ZDEtYTgzYy0yMGFlNGE0Y2Q3NTQiLCJ1bmlxdWVfbmFtZSI6IjU3Nzk3NDBkLWQwMjEtNDlkMS1hODNjLTIwYWU0YTRjZDc1NCIsImVtYWlsIjoidGVzdDFkMjNAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJuYmYiOjE3MTAxNzA2OTIsImV4cCI6MTcxMDI1NzA5MiwiaXNzIjoibmV0c3RvcmUiLCJhdWQiOiJuZXRzdG9yZSJ9.BPorsGTj2mp8R5DMZhOEZukURfklwpyhlLMdxec8fOY
@productId = 39b8b923-98dc-4a47-81fa-ac0f6e9c0eea

POST {{url}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "name": "Sample Jacket",
    "description": "Sample desc",
    "categoryId": 1,
    "brandId": 1,
    "model": "Sample model",
    "fabric": "Sample fabric",
    "gender": "Male",
    "agecategory": "Adult",
    "size": "M",
    "Color": "Black",
    "netprice": 1299
}

###

GET {{url}}?getby=brand&value=The%20North%20Face


###

GET {{url}}

###

GET {{url}}?getby=category&value=Down%20jackets

###

PATCH {{url}}/increase/{{productId}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "quantity": 10
}

###

PATCH {{url}}/decrease/{{productId}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "quantity": 1
}