@url = https://localhost:7240/orders-module/cart
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NzZkNmY2Ny05N2MwLTRjZmEtYjU4ZC03ZmJjZDE2N2Q5NWUiLCJ1bmlxdWVfbmFtZSI6IjU3NmQ2ZjY3LTk3YzAtNGNmYS1iNThkLTdmYmNkMTY3ZDk1ZSIsImVtYWlsIjoidGVzdG93eTEyM0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsIm5iZiI6MTcwMjIyMTgwOCwiZXhwIjoxNzAyMjI1NDA4LCJpc3MiOiJuZXRzdG9yZSIsImF1ZCI6Im5ldHN0b3JlIn0.0gsP43Waed8YAH9mztLmrmdCRWBSsslysmzvv7vruhQ


POST {{url}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "codeName": "1996-nuptse-xl-blue-adult",
    "quantity": 1
}

###

DELETE {{url}}?codeName=1996-nuptse-m-black-adult&quantity=1
Authorization: Bearer {{jwt}}


###

GET {{url}}
Authorization: Bearer {{jwt}}