@url = https://localhost:7240/orders-module/checkout
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Nzc5NzQwZC1kMDIxLTQ5ZDEtYTgzYy0yMGFlNGE0Y2Q3NTQiLCJ1bmlxdWVfbmFtZSI6IjU3Nzk3NDBkLWQwMjEtNDlkMS1hODNjLTIwYWU0YTRjZDc1NCIsImVtYWlsIjoidGVzdDFkMjNAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJuYmYiOjE3MTAxNzA2OTIsImV4cCI6MTcxMDI1NzA5MiwiaXNzIjoibmV0c3RvcmUiLCJhdWQiOiJuZXRzdG9yZSJ9.BPorsGTj2mp8R5DMZhOEZukURfklwpyhlLMdxec8fOY

GET {{url}}
Authorization: Bearer {{jwt}}

###

PUT {{url}}/shipment
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "city": "Gdańsk",
    "street": "Testowa 1",
    "PostalCode": "90-873",
    "ReceiverName": "Jan Testowy"
}

###

PUT {{url}}/payment
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "PaymentMethod": "CreditCard"
}

###

POST {{url}}/place-order
Authorization: Bearer {{jwt}}