@url = https://localhost:7240/orders-module/checkout
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNjRlMzUyMC04MTkyLTQ4OGQtOWJlNC02NzdlODE1YWE4MjkiLCJ1bmlxdWVfbmFtZSI6IjA2NGUzNTIwLTgxOTItNDg4ZC05YmU0LTY3N2U4MTVhYTgyOSIsImVtYWlsIjoidGVzdDFkMkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwibmJmIjoxNzA5NTUxNTAzLCJleHAiOjE3MDk2Mzc5MDMsImlzcyI6Im5ldHN0b3JlIiwiYXVkIjoibmV0c3RvcmUifQ.wyXcTfOpmr-Bpy0tC_5NmAqlpimiUVb1ux4wwFJFYcc

GET {{url}}
Authorization: Bearer {{jwt}}

###

PUT {{url}}/shipment
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "city": "Gdańsk",
    "street": "Testowa 1",
    "PostalCode": "90-873",
    "ReceiverName": "Jan Testowy"
}

###

PUT {{url}}/payment
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "PaymentMethod": "CreditCard"
}

###

POST {{url}}/place-order
Authorization: Bearer {{jwt}}