@url = https://localhost:7240/orders-module/checkout
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzZlM2JlOC02NGE1LTQ0NzItOGYzMy1lY2M2MWMzODZiMTMiLCJ1bmlxdWVfbmFtZSI6IjIzNmUzYmU4LTY0YTUtNDQ3Mi04ZjMzLWVjYzYxYzM4NmIxMyIsImVtYWlsIjoidGVzdG93eTEyM0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwibmJmIjoxNzA0NjU2MzY5LCJleHAiOjE3MDQ2NTk5NjksImlzcyI6Im5ldHN0b3JlIiwiYXVkIjoibmV0c3RvcmUifQ.I8kjT0NZgsf33XUkZBYZPAMIj1ajt8n6wKqSKzNmhk0

GET {{url}}
Authorization: Bearer {{jwt}}

###

PUT {{url}}/shipment
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "city": "Gdańsk",
    "street": "Testowa 1",
    "PostalCode": "90-873",
    "ReceiverName": "Jan Testowy"
}

###

PUT {{url}}/payment
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "PaymentMethod": "CreditCard"
}

###

POST {{url}}/place-order
Authorization: Bearer {{jwt}}