@url = https://localhost:7240/catalogs-module/categories
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNWZlNTQ3OC0zMTMyLTQzMGUtODk1Yy0yMjQwZTZkMzU4NmYiLCJ1bmlxdWVfbmFtZSI6IjM1ZmU1NDc4LTMxMzItNDMwZS04OTVjLTIyNDBlNmQzNTg2ZiIsImVtYWlsIjoidGVzdG93eTEyM0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJlbXBsb3llZSIsIm5iZiI6MTcwMTQzMDUyMywiZXhwIjoxNzAxNTE2OTIzLCJpc3MiOiJuZXRzdG9yZSIsImF1ZCI6Im5ldHN0b3JlIn0.WdqPcgP5_mB3p-Vi3KQJ8ulW951bQgG13EqgnsjOTlI

POST {{url}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "name": "Down jackets",
    "description": "Very comfy and warm jackets"
}

###

GET {{url}}/all


###

GET {{url}}?code=D-504
