@url = https://localhost:7240/catalogs-module/categories
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTNhOTA5YS04MTJhLTQwYmQtOWFjYi1lOTM4MzJhN2QzYjAiLCJ1bmlxdWVfbmFtZSI6IjZhM2E5MDlhLTgxMmEtNDBiZC05YWNiLWU5MzgzMmE3ZDNiMCIsImVtYWlsIjoidGVzdG93eTEyM0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsIm5iZiI6MTcwMTg4Mzc4MSwiZXhwIjoxNzAxOTcwMTgxLCJpc3MiOiJuZXRzdG9yZSIsImF1ZCI6Im5ldHN0b3JlIn0.BQiVdCXyfz1e1XHeN-enqJ-rqPwC9g5IsQggawjcuqg

POST {{url}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "name": "Down jackets",
    "description": "Very comfy and warm jackets"
}

###

PUT {{url}}/1
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "name": "Sample jackets",
    "description": "A new sample description"
}

###

DELETE {{url}}/1
Authorization: Bearer {{jwt}}


###

GET {{url}}/all


###

GET {{url}}?code=D-2223
