@url = https://localhost:7240/catalogs-module/categories
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Nzc5NzQwZC1kMDIxLTQ5ZDEtYTgzYy0yMGFlNGE0Y2Q3NTQiLCJ1bmlxdWVfbmFtZSI6IjU3Nzk3NDBkLWQwMjEtNDlkMS1hODNjLTIwYWU0YTRjZDc1NCIsImVtYWlsIjoidGVzdDFkMjNAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJuYmYiOjE3MDk5MDAyNTMsImV4cCI6MTcwOTk4NjY1MywiaXNzIjoibmV0c3RvcmUiLCJhdWQiOiJuZXRzdG9yZSJ9.NZiP6y390nCiAHhcpY2UhsCW7UwMcmFM2ExxEGv2JLU

POST {{url}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "name": "Down jackets",
    "description": "Very comfy and warm jackets"
}

###

PUT {{url}}/1
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "name": "Sample jackets",
    "description": "A new sample description"
}

###

DELETE {{url}}/1
Authorization: Bearer {{jwt}}


###

GET {{url}}/all


###

GET {{url}}?code=D-2223
